# Highly divisible triangular number
# Problem 12
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#     
#     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#     
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

compute_lower_divisors <- function(x) { # finds all divisors of x that are smaller than sqrt(x). The number of divisors of x is exactly twice this number.
    divisors <- NULL
    for(i in 1:floor(sqrt(x))){
        if(x %% i == 0){
            divisors <- c(divisors, i)
        }
    }
    divisors
}

triangle_num <- 1
increment <- 1

while(2 * length(compute_lower_divisors(triangle_num)) <= 500){
    increment <- increment + 1
    triangle_num <- triangle_num + increment
}

triangle_num
