# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib <- c(1L, 1L)
for(i in 3:40){
    fib[i] <- fib[i-1] + fib[i-2]
}
fib
sum(fib[fib < 4000000 & fib %% 2 == 0], na.rm = TRUE)
